// Templates data — all 9 wedding site descriptors

export interface TemplateData {
  slug: string;
  name: string;
  style: string;
  styleRu: string;
  structure: string;
  tagline: string;
  couple: string;
  coupleShort: string;
  date: string;
  dateIso: string;
  dateLong: string;
  dateMono: string;
  venue: string;
  city: string;
  rsvpDeadline: string;
  palette: {
    bg: string;
    bg2?: string;
    ink: string;
    ink2?: string;
    accent: string;
    paper?: string;
  };
  accent: string;
  ink: string;
  previewBg: string;
  quote: { text: string; author: string };
  story: Array<{ heading: string; body: string }>;
  program: Array<{ time: string; title: string; place: string; note?: string }>;
  details: { dressCode: string; gift: string; kids: string; transfer: string };
}

export const TEMPLATES: TemplateData[] = [
  {
    slug: 'editorial',
    name: 'Aurelia',
    style: 'Editorial Magazine',
    styleRu: 'Editorial',
    structure: 'Многополосный журнал с прогресс-баром чтения',
    tagline: 'Vogue-inspired serif, монохромные фото на разлёт, колонки и буквицы',
    couple: 'Алиса & Григорий',
    coupleShort: 'A · G',
    date: '14.09.2026',
    dateIso: '2026-09-14T16:00:00',
    dateLong: 'Четырнадцатого сентября 2026 года',
    dateMono: '14 · IX · MMXXVI',
    venue: 'Вилла Абрамцево',
    city: 'Подмосковье',
    rsvpDeadline: '14 августа 2026',
    palette: { bg: '#f5f1ea', bg2: '#ede7dc', ink: '#2a2418', ink2: '#6b5d4a', accent: '#a8896b', paper: '#ffffff' },
    accent: '#f5f1ea', ink: '#2a2418', previewBg: '#f5f1ea',
    quote: { text: 'Мы не хотели ни шатров, ни сюрпризов, ни тамады. Только семью, озеро и длинный стол с белым льном.', author: 'А. & Г.' },
    story: [
      { heading: 'Как это случилось', body: 'Алиса и Григорий познакомились на выставке в Венеции в октябре две тысячи двадцать третьего года. Он стоял у работы Агнес Мартин и делал вид, что понимает, зачем художнице минимум сорок восемь одинаковых линий. Она подошла и сказала: «Это не сорок восемь, а сорок девять.»' },
      { heading: 'Три года спустя', body: 'С тех пор — три года, две страны, один переезд и бесконечные разговоры о том, какой должна быть свадьба. В итоге — вилла на озере, ужин на террасе, сто двадцать гостей и никаких шатров.' },
    ],
    program: [
      { time: '16:00', title: 'Церемония', place: 'Terrazza del Lago', note: 'welcome aperitivo с 15:30' },
      { time: '18:30', title: 'Ужин', place: 'Длинный стол под оливами', note: 'шеф Лука Марчелли' },
      { time: '21:00', title: 'Танцы', place: 'Sala delle Muse', note: 'DJ Винцент до 02:00' },
    ],
    details: { dressCode: 'Cocktail attire, no white', gift: 'Ваше присутствие — лучший подарок', kids: 'Дети приветствуются до 21:00', transfer: 'Трансфер от отеля "Абрамцево" в 15:00' },
  },
  {
    slug: 'swiss',
    name: 'Grid-14',
    style: 'Minimal Swiss',
    styleRu: 'Swiss / минимал',
    structure: 'Split-screen: левая половина закреплена, правая скроллится',
    tagline: 'Сетка 12 колонок, Helvetica, типографика первична, максимум воздуха',
    couple: 'Мира & Лев',
    coupleShort: 'MIRA · LEV',
    date: '07.06.2026',
    dateIso: '2026-06-07T15:00:00',
    dateLong: '07 июня 2026',
    dateMono: '07.06.2026',
    venue: 'Депо. Москва',
    city: 'Москва',
    rsvpDeadline: '10 мая 2026',
    palette: { bg: '#ffffff', bg2: '#f3f3f3', ink: '#111111', ink2: '#555555', accent: '#ff0040', paper: '#fafafa' },
    accent: '#ffffff', ink: '#111111', previewBg: '#ffffff',
    quote: { text: 'Ясная линия. Короткое слово. Длинный стол. Всё.', author: 'M · L' },
    story: [
      { heading: '01 / Знакомство', body: '2021, типографская мастерская в Берлине. Мира искала шрифт, Лев — повод задержаться. Нашли и то и другое.' },
      { heading: '02 / Решение', body: 'Через 3 года совместных проектов решили: свадьба — как хороший плакат. Без лишнего.' },
    ],
    program: [
      { time: '15:00', title: 'Регистрация', place: 'Депо · Площадь 2' },
      { time: '16:30', title: 'Фото-сессия', place: 'Атриум' },
      { time: '18:00', title: 'Ужин', place: 'Main Hall' },
      { time: '22:00', title: 'Сет', place: 'Loft Floor' },
    ],
    details: { dressCode: 'Black / White / Grey', gift: 'No gifts please', kids: 'Adults only', transfer: 'Метро "Белорусская", 7 минут пешком' },
  },
  {
    slug: 'garden',
    name: 'Verbena',
    style: 'Garden Botanical',
    styleRu: 'Ботанический',
    structure: 'Центральная карточка с раскрывающимися секциями',
    tagline: 'Лавандовая палитра, акварель, soft sage, ручные штрихи',
    couple: 'Эмма & Матвей',
    coupleShort: 'E & M',
    date: '22.05.2026',
    dateIso: '2026-05-22T17:00:00',
    dateLong: 'Двадцать второго мая 2026',
    dateMono: '22 · 05 · 26',
    venue: 'Усадьба «Сиреневый сад»',
    city: 'Суздаль',
    rsvpDeadline: '22 апреля 2026',
    palette: { bg: '#eef2e6', bg2: '#e2e8d3', ink: '#2d3a26', ink2: '#5a6b4c', accent: '#a8b890', paper: '#f7faf0' },
    accent: '#eef2e6', ink: '#2d3a26', previewBg: '#eef2e6',
    quote: { text: 'Мы выбрали май — чтобы сирень успела распуститься, а вы — доехать.', author: 'Эмма' },
    story: [
      { heading: 'Прованс в Суздале', body: 'Мы долго думали, как совместить русскую усадьбу и нашу любовь к Провансу. Ответ оказался простым: лаванда растёт везде, где её посадить.' },
      { heading: 'Только свои', body: 'Сорок гостей, длинный стол в саду, домашние пироги, и никакой эстрады. Только живой квартет и сверчки.' },
    ],
    program: [
      { time: '17:00', title: 'Церемония в саду', place: 'Под старой яблоней' },
      { time: '18:00', title: 'Welcome-лимонад', place: 'Веранда' },
      { time: '19:00', title: 'Ужин', place: 'Оранжерея' },
      { time: '21:30', title: 'Костёр', place: 'Луг за домом' },
    ],
    details: { dressCode: 'Garden party · пастель, избегайте каблуков', gift: 'Живые цветы приветствуются', kids: 'Дети — да, няня будет', transfer: 'Автобус от Москвы в 12:00' },
  },
  {
    slug: 'dark',
    name: 'Noctis',
    style: 'Dark Luxe',
    styleRu: 'Dark luxe',
    structure: 'Полноэкранные секции с pin-скроллом и точечной навигацией',
    tagline: 'Чёрный + золото, кинематографичная композиция, поздний вечер',
    couple: 'София & Максим',
    coupleShort: 'S · M',
    date: '30.11.2026',
    dateIso: '2026-11-30T19:00:00',
    dateLong: 'Тридцатое ноября 2026',
    dateMono: '30.XI.MMXXVI',
    venue: 'Михайловский замок',
    city: 'Санкт-Петербург',
    rsvpDeadline: '30 октября 2026',
    palette: { bg: '#0d0b08', bg2: '#15110a', ink: '#f5f1ea', ink2: '#a89a7a', accent: '#d4b87a', paper: '#1a1510' },
    accent: '#d4b87a', ink: '#0d0b08', previewBg: '#0d0b08',
    quote: { text: 'Самая длинная ночь в году — та, которая превращается в рассвет вдвоём.', author: 'S · M' },
    story: [
      { heading: 'Ноябрь, Петербург', body: 'Мы выбрали самую тёмную ночь — потому что хороший свет виден только там, где есть чему темнеть. И потому что зимний Петербург невыразимо красив.' },
      { heading: 'Только близкие', body: 'Шестьдесят свечей, сорок гостей, три тоста и одно обещание. Мы хотим запомнить не торжество, а лица.' },
    ],
    program: [
      { time: '19:00', title: 'Коктейли', place: 'Белый зал' },
      { time: '20:00', title: 'Церемония', place: 'Парадная лестница' },
      { time: '21:00', title: 'Ужин', place: 'Георгиевский зал' },
      { time: '23:30', title: 'After', place: 'Подвал · джаз-квартет' },
    ],
    details: { dressCode: 'Black tie', gift: 'Wine list — ссылка в RSVP', kids: 'Only 16+', transfer: 'Трансфер от "Астории" в 18:30' },
  },
  {
    slug: 'brutalist',
    name: 'Konkret',
    style: 'Brutalist Type',
    styleRu: 'Бруталист',
    structure: 'Горизонтальный snap-scroll между блоками',
    tagline: 'Гигантские буквы, жёсткая сетка, никаких украшений, контраст',
    couple: 'ИРА × ЯН',
    coupleShort: 'IRA × YAN',
    date: '03/08/26',
    dateIso: '2026-08-03T14:00:00',
    dateLong: '03.08.2026',
    dateMono: '03/08/26',
    venue: 'ЛОФТ №4',
    city: 'Екатеринбург',
    rsvpDeadline: '20.07.26',
    palette: { bg: '#eae4d8', bg2: '#ffffff', ink: '#000000', ink2: '#444444', accent: '#ff3b1f', paper: '#f5f0e4' },
    accent: '#ff3b1f', ink: '#000000', previewBg: '#eae4d8',
    quote: { text: 'НЕ СВАДЬБА. СБОРКА.', author: '—' },
    story: [
      { heading: '01. ФАКТЫ', body: 'ИРА — архитектор. ЯН — звукорежиссёр. ВСТРЕТИЛИСЬ НА СТРОЙКЕ ТЕАТРА. ПОЖЕНИЛИСЬ ТАМ ЖЕ — ТЕПЕРЬ УЖЕ В ЛОФТЕ.' },
      { heading: '02. ПОВЕСТКА', body: 'БЕТОН. ЗВУК. ЕДА. ЛЮДИ. КОНЕЦ.' },
    ],
    program: [
      { time: '14:00', title: 'ВХОД', place: 'ВОРОТА 4' },
      { time: '15:00', title: 'РЕГИСТРАЦИЯ', place: 'ЭТАЖ 1' },
      { time: '17:00', title: 'УЖИН', place: 'ЦЕХ' },
      { time: '21:00', title: 'СЕТ', place: 'СЦЕНА' },
    ],
    details: { dressCode: 'ОДЕНЬТЕ ТО, В ЧЁМ НЕ ЖАЛКО', gift: 'НЕ НАДО', kids: '18+', transfer: 'ТРАМВАЙ 15 ДО "ВИЗ"' },
  },
  {
    slug: 'letterpress',
    name: 'Maisonneuve',
    style: 'Vintage Letterpress',
    styleRu: 'Letterpress / book-fold',
    structure: 'Книжный разворот: 3 страницы с листанием',
    tagline: 'Тиснение, старая бумага, классическая композиция, ручной труд',
    couple: 'Элеонора & Фёдор',
    coupleShort: 'E & F',
    date: '14.06.2026',
    dateIso: '2026-06-14T13:00:00',
    dateLong: 'Четырнадцатого июня MMXXVI года',
    dateMono: 'XIV · VI · MMXXVI',
    venue: 'Усадьба Карабиха',
    city: 'Ярославль',
    rsvpDeadline: '14 мая 2026',
    palette: { bg: '#ebe1cc', bg2: '#dfd4b8', ink: '#3a2a1a', ink2: '#6b5a3f', accent: '#c9a878', paper: '#f2e9d0' },
    accent: '#c9a878', ink: '#3a2a1a', previewBg: '#ebe1cc',
    quote: { text: 'Имеем честь пригласить Вас разделить с нами день, о котором мы мечтали тихо, долго и очень вдвоём.', author: 'Г-жа Элеонора и Г-н Фёдор' },
    story: [
      { heading: 'О знакомстве', body: 'Мы встретились в библиотеке иностранной литературы в среду. Он искал Борхеса, она — тишины. Нашли друг друга.' },
      { heading: 'О семье', body: 'Три поколения наших семей будут за одним столом. Двадцать шесть кузенов. Один прадед, который помнит довоенный Ярославль.' },
    ],
    program: [
      { time: '13:00', title: 'Венчание', place: 'Храм Спаса на Городу' },
      { time: '15:00', title: 'Чай с вареньем', place: 'Веранда усадьбы' },
      { time: '17:00', title: 'Званый ужин', place: 'Каминный зал' },
      { time: '21:00', title: 'Вальсы', place: 'Паркетная гостиная' },
    ],
    details: { dressCode: 'Classic formal · длинное платье, костюм-тройка', gift: 'Книги — всегда хорошо', kids: 'С удовольствием', transfer: 'Электричка Москва-Ярославль 07:05' },
  },
  {
    slug: 'wabisabi',
    name: 'Kumo',
    style: 'Japanese Wabi-Sabi',
    styleRu: 'Wabi-sabi / parallax',
    structure: 'Сторителлинг с параллаксом и медленным проявлением каллиграфии',
    tagline: 'Тушь, пустота, асимметрия, Noto Serif JP, сакура и туман',
    couple: 'Юлия & Роман',
    coupleShort: '結',
    date: '11.04.2026',
    dateIso: '2026-04-11T15:00:00',
    dateLong: 'Одиннадцатое апреля 2026',
    dateMono: '2026.04.11',
    venue: 'Мыс Тобизина',
    city: 'Владивосток',
    rsvpDeadline: '11 марта 2026',
    palette: { bg: '#f2ede4', bg2: '#e8dfd0', ink: '#1a1814', ink2: '#5c5550', accent: '#d85a3b', paper: '#fbf6ec' },
    accent: '#d85a3b', ink: '#1a1814', previewBg: '#f2ede4',
    quote: { text: '一期一会 — один раз, одна встреча. Всё остальное — надстройка.', author: '結 · Musubi' },
    story: [
      { heading: 'Случайность', body: 'Мы встретились в одной сакуровой аллее в Киото в марте 2022. У Юлии был поломанный зонт, у Романа — лишний. Поделились. Не расстались.' },
      { heading: 'Возвращение', body: 'Четыре года спустя — Владивосток, где сопки падают в море. Тихо. Сто человек. Вишня. Сакэ.' },
    ],
    program: [
      { time: '15:00', title: '茶 · Чайная церемония', place: 'Павильон у воды' },
      { time: '16:00', title: '式 · Церемония', place: 'Обрыв над бухтой' },
      { time: '18:00', title: '宴 · Пир', place: 'Длинный стол с видом на Японское море' },
      { time: '21:00', title: '月 · Луна', place: 'Прогулка по берегу' },
    ],
    details: { dressCode: 'Linen, нейтральные тона', gift: 'Origami приветствуется', kids: 'Да', transfer: 'Трансфер из Владивостока в 13:00' },
  },
  {
    slug: 'polaroid',
    name: 'Super-8',
    style: 'Polaroid / Film',
    styleRu: 'Polaroid / timeline',
    structure: 'Вертикальный timeline дня с карточками-поляроидами',
    tagline: 'Рассыпанные поляроиды, скотч, ручной скрипт, тёплые плёночные тона',
    couple: 'Даша & Кирилл',
    coupleShort: 'D & K',
    date: '18.07.2026',
    dateIso: '2026-07-18T17:00:00',
    dateLong: '18 июля 2026',
    dateMono: '18.07.2026',
    venue: 'Дикий пляж · Сочи',
    city: 'Сочи',
    rsvpDeadline: '01 июля 2026',
    palette: { bg: '#f0ebe0', bg2: '#e5dcc8', ink: '#2a2418', ink2: '#6b5d4a', accent: '#e8d4a8', paper: '#ffffff' },
    accent: '#e8d4a8', ink: '#2a2418', previewBg: '#f0ebe0',
    quote: { text: 'Поставили камеру на таймер в 2019 — до сих пор не успели снять её со штатива.', author: 'Д & К' },
    story: [
      { heading: 'Одно лето', body: 'Мы познакомились в июле 2019 на даче у общего друга. Четыре дня подряд играли в бадминтон и спорили о том, кто лучше фотографирует закат.' },
      { heading: 'Семь лет и триста плёнок', body: 'С тех пор — 47 поездок, 312 отснятых плёнок, 2 кота и одно обещание. Сегодня — последний кадр этой главы.' },
    ],
    program: [
      { time: '10:00', title: 'Morning coffee', place: 'Веранда нашего дома', note: 'для самых близких' },
      { time: '15:00', title: 'Welcome drinks', place: 'У моря' },
      { time: '17:00', title: 'Церемония', place: 'На кромке воды', note: 'босиком, если хотите' },
      { time: '19:00', title: 'Ужин у костра', place: 'Длинный стол на песке' },
      { time: '22:00', title: 'Танцы до волн', place: 'Плёночный проектор, сет до 03:00' },
    ],
    details: { dressCode: 'Summer casual · лён, хлопок, без туфель', gift: 'Плёнка 35мм — идеально', kids: 'Обязательно', transfer: 'Встречаем в аэропорту Сочи' },
  },
  {
    slug: 'artdeco',
    name: 'Palais',
    style: 'Art Deco',
    styleRu: 'Art Deco / tabs',
    structure: 'Мини-сайт с табами и якорной навигацией',
    tagline: 'Geometric, Gatsby, metallic, Cinzel — строгая симметрия и золото',
    couple: 'Вера & Николай',
    coupleShort: 'V · N',
    date: '12.12.2026',
    dateIso: '2026-12-12T19:00:00',
    dateLong: 'Двенадцатое декабря 2026',
    dateMono: 'XII · XII · MMXXVI',
    venue: 'Красная Поляна',
    city: 'Сочи',
    rsvpDeadline: '12 ноября 2026',
    palette: { bg: '#0f0f18', bg2: '#18182a', ink: '#f5f1ea', ink2: '#9e9080', accent: '#b8975a', paper: '#1a1a2c' },
    accent: '#b8975a', ink: '#0f0f18', previewBg: '#0f0f18',
    quote: { text: 'Зима, золото, горы. Остальное — обстоятельства.', author: 'V · N' },
    story: [
      { heading: 'Опера, 2019', body: 'Вера пела в хоре, Николай сидел в третьем ряду с ошибочным билетом. После спектакля извинился. Через год пригласил на "Риголетто" — но уже с правильным билетом.' },
      { heading: 'Горы и голос', body: 'Сегодня мы соединяем две наши страсти — высоту и сцену. Камерный хор выступит для вас прямо на балконе отеля, с видом на Аибгу.' },
    ],
    program: [
      { time: '19:00', title: 'Welcome', place: 'Palace Lobby · шампанское' },
      { time: '20:00', title: 'Церемония', place: 'Ballroom · с живым оркестром' },
      { time: '21:00', title: 'Gala Dinner', place: 'Grand Hall' },
      { time: '23:00', title: 'Opera Suite', place: 'After-вечеринка до 04:00' },
    ],
    details: { dressCode: 'White tie · gold accents welcome', gift: 'Wish list на сайте отеля', kids: 'Adults only', transfer: 'Трансфер от аэропорта Сочи включён' },
  },
  {
    slug: 'neon',
    name: 'Cipher',
    style: 'Neon / Glitch',
    styleRu: 'Neon / Glitch',
    structure: 'Полноэкранные секции с неоновым свечением и глитч-эффектами',
    tagline: 'Тёмный фон, неон, код, киберпанк — для тех, кто не хочет "как все"',
    couple: 'Нина & Артём',
    coupleShort: 'N × A',
    date: '31.10.2026',
    dateIso: '2026-10-31T22:00:00',
    dateLong: 'Тридцать первого октября 2026',
    dateMono: '31.10.2026',
    venue: 'Флакон Design Factory',
    city: 'Москва',
    rsvpDeadline: '10 октября 2026',
    palette: { bg: '#07070f', bg2: '#0e0e1c', ink: '#eeeeff', ink2: '#8888bb', accent: '#c724ff', paper: '#12121f' },
    accent: '#c724ff', ink: '#07070f', previewBg: '#07070f',
    quote: { text: 'Мы познакомились в 3 ночи на хакатоне. Никто из нас не решил задачу. Но мы нашли кое-что лучше.', author: 'N × A' },
    story: [
      { heading: 'Хакатон, 2022', body: 'Нина писала бэкенд, Артём — фронтенд. Через 40 часов без сна они поняли, что их архитектуры несовместимы. Зато они сами — вполне.' },
      { heading: 'Три года спустя', body: 'Сейчас у них общий репозиторий, один кот по имени Null и свадьба в Хэллоуин. Потому что "когда ещё, если не сейчас".' },
    ],
    program: [
      { time: '22:00', title: 'Инициализация', place: 'Вход · Флакон' },
      { time: '23:00', title: 'Церемония', place: 'Цех №2 · light show' },
      { time: '00:00', title: 'Ужин & сет', place: 'Главный зал', note: 'live electronics до 05:00' },
    ],
    details: { dressCode: 'Anything neon или all black', gift: 'BTC-адрес в RSVP', kids: '18+ only', transfer: 'Метро "Дмитровская", 8 минут пешком' },
  },
  {
    slug: 'cottage',
    name: 'Rosehip',
    style: 'Cottagecore',
    styleRu: 'Коттеджкор',
    structure: 'Уютный скролл с акварельными иллюстрациями и тёплыми секциями',
    tagline: 'Земляника, льняные скатерти, полевые цветы и старый сад — как будто сказка',
    couple: 'Аня & Петя',
    coupleShort: 'A & P',
    date: '15.08.2026',
    dateIso: '2026-08-15T16:00:00',
    dateLong: 'Пятнадцатого августа 2026',
    dateMono: '15 · VIII · 2026',
    venue: 'Усадьба Суханово',
    city: 'Подмосковье',
    rsvpDeadline: '15 июля 2026',
    palette: { bg: '#fdf5e8', bg2: '#f5e8d5', ink: '#3d2c1e', ink2: '#7a5c40', accent: '#c8855a', paper: '#fffbf2' },
    accent: '#c8855a', ink: '#3d2c1e', previewBg: '#fdf5e8',
    quote: { text: 'Мы хотели свадьбу, на которую сами бы с удовольствием пришли. Долго искали и наконец поняли — такой сад уже есть у бабушки.', author: 'Аня' },
    story: [
      { heading: 'Дача, 2021', body: 'Аня и Петя познакомились на общей даче у друга в августе 2021. Она собирала малину, он чинил велосипед. Оба делали вид, что заняты делом.' },
      { heading: 'Наш август', body: 'С тех пор каждое лето они возвращаются в Суханово. В этот раз — с кольцами, гостями и длинным столом прямо среди яблонь.' },
    ],
    program: [
      { time: '16:00', title: 'Встреча в саду', place: 'Яблоневая аллея' },
      { time: '17:00', title: 'Церемония', place: 'Под старым дубом' },
      { time: '18:30', title: 'Пикник-ужин', place: 'Луг · длинные столы', note: 'домашняя еда, живая музыка' },
      { time: '21:00', title: 'Костёр и звёзды', place: 'Берег пруда' },
    ],
    details: { dressCode: 'Льён, хлопок, пастель — никаких каблуков', gift: 'Саженец или варенье — шутим, но не очень', kids: 'Дети — сердце праздника', transfer: 'Автобус от м. Домодедовская в 14:30' },
  },
  {
    slug: 'memphis',
    name: 'Fiesta',
    style: 'Memphis 80s',
    styleRu: 'Мемфис / 80-е',
    structure: 'Пёстрая сетка цветных блоков, нет ничего серьёзного',
    tagline: 'Яркие цвета, геометрия, зигзаги — дизайн как вечеринка',
    couple: 'Вика & Андрей',
    coupleShort: 'V & A',
    date: '04.07.2026',
    dateIso: '2026-07-04T17:00:00',
    dateLong: 'Четвёртого июля 2026',
    dateMono: '04.07.2026',
    venue: 'Ткачи · лофт',
    city: 'Санкт-Петербург',
    rsvpDeadline: '20 июня 2026',
    palette: { bg: '#fffbf5', bg2: '#fff0e0', ink: '#111111', ink2: '#444444', accent: '#ff3f5e', paper: '#ffffff' },
    accent: '#ff3f5e', ink: '#111111', previewBg: '#fffbf5',
    quote: { text: 'Серьёзность — переоценённое качество. Мы планируем танцевать до закрытия.', author: 'V & A' },
    story: [
      { heading: 'Вечеринка, 2020', body: 'Вика диджеила, Андрей пришёл за компанию и остался до утра. Потом он сказал, что пришёл за музыкой. Она не поверила.' },
      { heading: 'Шесть лет дискотек', body: 'Шесть лет, двенадцать городов, сотни треков и один общий плейлист на двоих. Теперь у этого плейлиста будет финальный трек — наша свадьба.' },
    ],
    program: [
      { time: '17:00', title: 'Welcome & коктейли', place: 'Двор Ткачей' },
      { time: '18:00', title: 'Церемония', place: 'Большой лофт' },
      { time: '19:30', title: 'Ужин', place: 'Цветные столы · live band' },
      { time: '22:00', title: 'Диско', place: 'Вика за пультом до 04:00' },
    ],
    details: { dressCode: 'Яркое! Запрещено приходить в сером', gift: 'Виниловая пластинка — идеально', kids: 'До 21:00 — да, после — тихая комната', transfer: 'Трамвай 16 до "Лоцманской"' },
  },
];

