// The 9 template descriptors — used by portfolio grid, /templates index, and demo router

const TEMPLATES = [
  {
    slug: 'editorial',
    name: 'Aurelia',
    style: 'Editorial Magazine',
    styleRu: 'Editorial',
    tagline: 'Vogue-inspired serif, монохромные фото на разлёт',
    couple: 'Алиса & Григорий',
    date: '14.09.2026',
    venue: 'Villa Erba, Como',
    accent: '#f5f1ea',
    ink: '#2a2418',
    previewBg: '#f5f1ea',
  },
  {
    slug: 'swiss',
    name: 'Grid-14',
    style: 'Minimal Swiss',
    styleRu: 'Swiss / минимал',
    tagline: 'Сетка 12 колонок, Helvetica, типографика первична',
    couple: 'Mira & Leo',
    date: '07.06.2026',
    venue: 'Zürich, CH',
    accent: '#ffffff',
    ink: '#111111',
    previewBg: '#ffffff',
  },
  {
    slug: 'garden',
    name: 'Verbena',
    style: 'Garden Botanical',
    styleRu: 'Ботанический',
    tagline: 'Акварельные флора-элементы, soft sage, ручные штрихи',
    couple: 'Ella & Matteo',
    date: '22.05.2026',
    venue: 'Tuscany villa, IT',
    accent: '#eef2e6',
    ink: '#2d3a26',
    previewBg: '#eef2e6',
  },
  {
    slug: 'dark',
    name: 'Noctis',
    style: 'Dark Luxe',
    styleRu: 'Dark luxe',
    tagline: 'Чёрный + золото, cinematic crop, late-night wedding',
    couple: 'Sofia & Max',
    date: '30.11.2026',
    venue: 'Palais, Paris',
    accent: '#d4b87a',
    ink: '#0d0b08',
    previewBg: '#0d0b08',
  },
  {
    slug: 'brutalist',
    name: 'Konkret',
    style: 'Brutalist Type',
    styleRu: 'Бруталист',
    tagline: 'Гигантские буквы, жёсткая сетка, никаких украшений',
    couple: 'IRA × JAN',
    date: '03/08/26',
    venue: 'Berlin Kreuzberg',
    accent: '#ff3b1f',
    ink: '#000000',
    previewBg: '#eae4d8',
  },
  {
    slug: 'letterpress',
    name: 'Maisonneuve',
    style: 'Vintage Letterpress',
    styleRu: 'Letterpress',
    tagline: 'Тиснение, старая бумага, классическая композиция',
    couple: 'Eleanor & Theodore',
    date: 'June XIV, MMXXVI',
    venue: 'Orléans, France',
    accent: '#c9a878',
    ink: '#3a2a1a',
    previewBg: '#ebe1cc',
  },
  {
    slug: 'wabisabi',
    name: 'Kumo',
    style: 'Japanese Wabi-Sabi',
    styleRu: 'Wabi-sabi',
    tagline: 'Тушь, пустота, асимметрия, Noto Serif JP',
    couple: 'Yuki & Ren',
    date: '2026.04.11',
    venue: 'Kyoto, 京都',
    accent: '#d85a3b',
    ink: '#1a1814',
    previewBg: '#f2ede4',
  },
  {
    slug: 'polaroid',
    name: 'Super-8',
    style: 'Polaroid / Film',
    styleRu: 'Polaroid',
    tagline: 'Рассыпанные поляроиды, скотч, ручной скрипт',
    couple: 'Dasha & Kirill',
    date: '18.07.2026',
    venue: 'Montenegro coast',
    accent: '#e8d4a8',
    ink: '#2a2418',
    previewBg: '#f0ebe0',
  },
  {
    slug: 'artdeco',
    name: 'Palais',
    style: 'Art Deco',
    styleRu: 'Art Deco',
    tagline: 'Geometric, Gatsby, metallic, Cinzel',
    couple: 'Vera & Nikolai',
    date: 'XII · XII · MMXXVI',
    venue: 'Monaco',
    accent: '#b8975a',
    ink: '#0f0f18',
    previewBg: '#0f0f18',
  },
];

Object.assign(window, { TEMPLATES });
